### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by temujin9** [portworx/px-dev#12]
Is this open source?

**Comment by jsilberm** [comment]
Portworx offers a freely-available developer version on this Github site.   But the code is not open source.   (P.S.  I'll be presenting at the upcoming Docker Meetup in Austin next Tues 9/6.  Please stop by).

**Comment by temujin9** [comment]
Thanks, but I'm not really into closed source solutions, and definitely not in this particular product space. Cheers!
