### ISSUE TITLE
Error launch px-dev in Rancher 1.2 + RancherOS 0.7.0

### ISSUE THREAD

**Issue by galindro** [portworx/px-dev#16]
After launch the portworx service from Rancher Catalog, the services doesn't start.

Here are the logs from one container. I've enabled [kernel-headers in rancheros](https://docs.rancher.com/os/configuration/kernel-modules-kernel-headers/) before start the stack.

```bash
12/7/2016 1:48:57 PMWed Dec  7 15:48:57 UTC 2016 : Running on Linux ip-10-0-3-75.sa-east-1.compute.internal 4.4.21-rancher #1 SMP Sat Oct 15 07:53:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
12/7/2016 1:48:57 PMRequired size for /dev/shm is  293601280 is less than 67108864
12/7/2016 1:48:57 PMchecking /usr/src/kernels/4.4.21-rancher
12/7/2016 1:48:57 PMchecking /usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:48:57 PMchecking /lib/modules/4.4.21-rancher/build
12/7/2016 1:48:57 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:48:57 PMchecking /usr/src/linux
12/7/2016 1:48:57 PMLoaded plugins: fastestmirror
12/7/2016 1:48:57 PMRepodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
12/7/2016 1:49:01 PMhttp://mirror.globo.com/epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
12/7/2016 1:49:01 PMTrying other mirror.
12/7/2016 1:49:03 PMhttps://mirror.cedia.org.ec/fedora-epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
12/7/2016 1:49:03 PMTrying other mirror.
12/7/2016 1:49:10 PMDetermining fastest mirrors
12/7/2016 1:49:10 PM * base: centos.xpg.com.br
12/7/2016 1:49:10 PM * epel: mirror.globo.com
12/7/2016 1:49:10 PM * extras: centos.xpg.com.br
12/7/2016 1:49:10 PM * updates: centos.xpg.com.br
12/7/2016 1:49:13 PMNo package kernel-headers-4.4.21-rancher available.
12/7/2016 1:49:13 PMError: Nothing to do
12/7/2016 1:49:13 PMLoaded plugins: fastestmirror
12/7/2016 1:49:13 PMLoading mirror speeds from cached hostfile
12/7/2016 1:49:13 PM * base: centos.xpg.com.br
12/7/2016 1:49:13 PM * epel: mirror.globo.com
12/7/2016 1:49:13 PM * extras: centos.xpg.com.br
12/7/2016 1:49:13 PM * updates: centos.xpg.com.br
12/7/2016 1:49:13 PMNo package kernel-devel-4.4.21-rancher available.
12/7/2016 1:49:13 PMError: Nothing to do
12/7/2016 1:49:13 PMchecking /usr/src/kernels/4.4.21-rancher
12/7/2016 1:49:13 PMchecking /usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:13 PMchecking /lib/modules/4.4.21-rancher/build
12/7/2016 1:49:13 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:13 PMchecking /usr/src/linux
12/7/2016 1:49:13 PMChecking short path for KVERSION 4.4.21-rancher.el7.x86_64
12/7/2016 1:49:13 PMchecking /usr/src/kernels/4.4.21-rancher.el7.x86_64
12/7/2016 1:49:13 PMchecking /usr/src/linux-headers-4.4.21-rancher.el7.x86_64
12/7/2016 1:49:13 PMchecking /lib/modules/4.4.21-rancher.el7.x86_64/build
12/7/2016 1:49:13 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher.el7.x86_64
12/7/2016 1:49:13 PMchecking /usr/src/linux
12/7/2016 1:49:13 PMLoaded plugins: fastestmirror
12/7/2016 1:49:13 PMLoading mirror speeds from cached hostfile
12/7/2016 1:49:13 PM * base: centos.xpg.com.br
12/7/2016 1:49:13 PM * epel: mirror.globo.com
12/7/2016 1:49:13 PM * extras: centos.xpg.com.br
12/7/2016 1:49:13 PM * updates: centos.xpg.com.br
12/7/2016 1:49:14 PMNo package kernel-headers-4.4.21-rancher.el7.x86_64 available.
12/7/2016 1:49:14 PMError: Nothing to do
12/7/2016 1:49:14 PMLoaded plugins: fastestmirror
12/7/2016 1:49:14 PMLoading mirror speeds from cached hostfile
12/7/2016 1:49:14 PM * base: centos.xpg.com.br
12/7/2016 1:49:14 PM * epel: mirror.globo.com
12/7/2016 1:49:14 PM * extras: centos.xpg.com.br
12/7/2016 1:49:14 PM * updates: centos.xpg.com.br
12/7/2016 1:49:14 PMNo package kernel-devel-4.4.21-rancher.el7.x86_64 available.
12/7/2016 1:49:14 PMError: Nothing to do
12/7/2016 1:49:14 PMchecking /usr/src/kernels/4.4.21-rancher.el7.x86_64
12/7/2016 1:49:14 PMchecking /usr/src/linux-headers-4.4.21-rancher.el7.x86_64
12/7/2016 1:49:14 PMchecking /lib/modules/4.4.21-rancher.el7.x86_64/build
12/7/2016 1:49:14 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher.el7.x86_64
12/7/2016 1:49:14 PMchecking /usr/src/linux
12/7/2016 1:49:14 PMchecking /usr/src/kernels/4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /lib/modules/4.4.21-rancher/build
12/7/2016 1:49:14 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux
12/7/2016 1:49:14 PMchecking /usr/src/kernels/4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /lib/modules/4.4.21-rancher/build
12/7/2016 1:49:14 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux
12/7/2016 1:49:14 PMchecking /usr/src/kernels/4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /lib/modules/4.4.21-rancher/build
12/7/2016 1:49:14 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux
12/7/2016 1:49:14 PMchecking /usr/src/kernels/4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /lib/modules/4.4.21-rancher/build
12/7/2016 1:49:14 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.4.21-rancher
12/7/2016 1:49:14 PMchecking /usr/src/linux
12/7/2016 1:49:14 PMFailed to install/locate kernel headers for 4.4.21-rancher
12/7/2016 1:49:14 PMFailed to load PX module dependencies
```

**Comment by asthomasdk** [comment]
Although different versions of Rancher (1.5.3) and RancherOS (0.9.0) - I'd also like to know if there is support for RancherOS with px-dev - and what the steps are to set this up. 

Also getting similar errors: 

`
3/27/2017 5:51:42 PMchecking /usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:42 PMchecking /usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:42 PMchecking /lib/modules/4.9.15-rancher/build
3/27/2017 5:51:42 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:42 PMchecking /usr/src/linux
3/27/2017 5:51:42 PMchecking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:42 PMchecking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:43 PMchecking /usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:43 PMchecking /usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:43 PMchecking /lib/modules/4.9.15-rancher/build
3/27/2017 5:51:43 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:43 PMchecking /usr/src/linux
3/27/2017 5:51:43 PMchecking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:43 PMchecking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:43 PMchecking /usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:43 PMchecking /usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:43 PMchecking /lib/modules/4.9.15-rancher/build
3/27/2017 5:51:43 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:43 PMchecking /usr/src/linux
3/27/2017 5:51:43 PMchecking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:43 PMchecking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:44 PMchecking /usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:44 PMchecking /usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:44 PMchecking /lib/modules/4.9.15-rancher/build
3/27/2017 5:51:44 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:44 PMchecking /usr/src/linux
3/27/2017 5:51:44 PMchecking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:44 PMchecking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:44 PMchecking /usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:44 PMchecking /usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:44 PMchecking /lib/modules/4.9.15-rancher/build
3/27/2017 5:51:44 PMchecking /tmp/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:44 PMchecking /usr/src/linux
3/27/2017 5:51:44 PMchecking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.9.15-rancher
3/27/2017 5:51:44 PMchecking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.9.15-rancher
3/27/2017 5:51:45 PMDownloading from: http://mirrors.portworx.com/build-results/pxfuse/for-installer/x86_64/4.9.15-rancher/packages...
3/27/2017 5:51:45 PMDownload linux-headers failed...
3/27/2017 5:51:45 PMFailed to install/locate kernel headers for 4.9.15-rancher
3/27/2017 5:51:45 PMFailed to load PX module dependencies
`

**Comment by gourao** [comment]
PX either needs to have the kernel headers for your kernel available on the system, or for the node to have internet access so it can download them.  Can you confirm if either of these are possible and then restart PX?

**Comment by venkatpx** [comment]
@galindro  @asthomasdk Is this still an issue for you or you were able to get past this?

**Comment by galindro** [comment]
@venkatpx I'm not using Rancher anymore... I'm using docker swarm.

**Comment by asthomasdk** [comment]
I have not tried using px-dev for a while now - so I am not sure if we still have issues with this on our setup. We are still using Rancher and on 1.6.7 atm.

**Comment by jrivera-px** [comment]
RancherOS headers are installed in /lib/modules(http://rancher.com/docs/os/configuration/kernel-modules-kernel-headers/).   So  ‘-v /lib/modules:lib/modules’ needs to be added to the run command.

**Comment by homeles** [comment]
I'm having the same issue and looks to be related to the proxy. try running the px-dev container with -e http_proxy, and that will solve the problem.
