### ISSUE TITLE
404 Not Found during download of kernel headers for 4.4.59-boot2docker

### ISSUE THREAD

**Issue by aoakalin** [portworx/px-dev#24]
Probably similar to #16, I'm having problems running px-dev on my docker-machine.

During launch of the container, it looks for [http://mirrors.portworx.com/build-results/pxfuse/for-installer/x86_64/4.4.59-boot2docker/packages](http://mirrors.portworx.com/build-results/pxfuse/for-installer/x86_64/4.4.59-boot2docker/packages); but it fails, when I checked the URL at my browser, I get 404 not found.

docker version:
>Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64

> Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: true

docker-machine version:
> docker-machine.exe version 0.10.0, build 76ed2a6

log for the container:
> Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-4.4.59-boot2docker
E: Couldn't find any package by glob 'linux-headers-4.4.59-boot2docker'
E: Couldn't find any package by regex 'linux-headers-4.4.59-boot2docker'
checking /hostusr/src/kernels/4.4.59-boot2docker
checking /hostusr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/kernels/4.4.59-boot2docker
checking /usr/src/linux-headers-4.4.59-boot2docker
checking /lib/modules/4.4.59-boot2docker/build
checking /tmp/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/linux
checking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.4.59-boot2docker
checking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /hostusr/src/kernels/4.4.59-boot2docker
checking /hostusr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/kernels/4.4.59-boot2docker
checking /usr/src/linux-headers-4.4.59-boot2docker
checking /lib/modules/4.4.59-boot2docker/build
checking /tmp/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/linux
checking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.4.59-boot2docker
checking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /hostusr/src/kernels/4.4.59-boot2docker
checking /hostusr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/kernels/4.4.59-boot2docker
checking /usr/src/linux-headers-4.4.59-boot2docker
checking /lib/modules/4.4.59-boot2docker/build
checking /tmp/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/linux
checking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.4.59-boot2docker
checking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /hostusr/src/kernels/4.4.59-boot2docker
checking /hostusr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/kernels/4.4.59-boot2docker
checking /usr/src/linux-headers-4.4.59-boot2docker
checking /lib/modules/4.4.59-boot2docker/build
checking /tmp/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/linux
checking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.4.59-boot2docker
checking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /hostusr/src/kernels/4.4.59-boot2docker
checking /hostusr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/kernels/4.4.59-boot2docker
checking /usr/src/linux-headers-4.4.59-boot2docker
checking /lib/modules/4.4.59-boot2docker/build
checking /tmp/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
checking /usr/src/linux
checking /tmp/px_workspace/kernel_headers/usr/src/kernels/4.4.59-boot2docker
checking /tmp/px_workspace/kernel_headers/usr/src/linux-headers-4.4.59-boot2docker
Downloading from: http://mirrors.portworx.com/build-results/pxfuse/for-installer/x86_64/4.4.59-boot2docker/packages...
Download linux-kbuild failed...
Failed to install/locate kernel headers for 4.4.59-boot2docker
Failed to load PX module dependencies

Any suggestions?

**Comment by jsilberm** [comment]
Any chance you could spin up a Linux VM and run px-dev from within there?
We require Linux (any), and will not currently work on Windows.
What are the Windows apps that you want to be running with px-dev?

**Comment by aoakalin** [comment]
I plan on using px-dev on Linux machines in the end but I'm trying to learn how to use it on a virtual cluster on my windows 7 computer for now. I'm using docker-machine with Oracle VM Virtualbox to spin up a Linux VM from boot2docker.iso. Is this not supported?

Here are the commands I have used in exact order:
```
docker-machine create \
        -d virtualbox \
        --engine-opt experimental=true \
	--virtualbox-cpu-count="2" \
	--virtualbox-memory="2048" \
	--virtualbox-disk-size="8192" \
        node-1

eval `docker-machine env node-1`

docker run -v \
  /data/varlib/etcd \
  -p 4001:4001 \
  -d \
  portworx/etcd:latest

sudo su

mkdir -p /etc/pwx
mkdir -p /opt/pwx/bin
mkdir -p /var/lib/osd
mkdir -p /var/cores

mount --make-shared /

docker run --restart=always --name px -d --net=host \
  --privileged=true                             \
  -v /run/docker/plugins:/run/docker/plugins    \
  -v /var/lib/osd:/var/lib/osd:shared           \
  -v /dev:/dev                                  \
  -v /etc/pwx:/etc/pwx                          \
  -v /opt/pwx/bin:/export_bin:shared            \
  -v /var/run/docker.sock:/var/run/docker.sock  \
  -v /var/cores:/var/cores                      \
  -v /usr/src:/usr/src                           \
  --ipc=host                                    \
  portworx/px-dev -daemon -k etcd://localhost:4001 -c cluster1 -s /dev/sda1
```

**Comment by jsilberm** [comment]
Not currently supported.   The docker engine must be running on a Linux host for now.  Sorry.   Hopefully you can find a native Linux host to start playing with px-dev
