### ISSUE TITLE
PX starts in maintenance mode

### ISSUE THREAD

**Issue by abienkowski** [portworx/px-dev#36]
$ /opt/pwx/bin/pxctl status
Status: PX is in maintenance Mode. Use the service mode option to repair the system
License: PX-Developer
Node ID: 29a24ea7-a84d-4142-a412-b7fb83fbc695
        IP: 192.168.10.68
        Local Storage Pool: 1 pool
        POOL    IO_PRIORITY     RAID_LEVEL      USABLE  USED    STATUS  ZONE    REGION
        0       HIGH            raid0           200 GiB 0 B     Offline default default
        Local Storage Devices: 2 devices
        Device  Path            Media Type              Size            Last-Scan
        0:1     /dev/sdb        STORAGE_MEDIUM_MAGNETIC 100 GiB         11 Jul 17 01:30 UTC
        0:2     /dev/sdc        STORAGE_MEDIUM_MAGNETIC 100 GiB         11 Jul 17 01:30 UTC
        total                   -                       200 GiB
Cluster Summary
        Cluster ID: devops-cluster-01
        Cluster UUID: 59bbd96e-a802-4718-94cd-82fb74a22ae9
        IP              ID                                      Used            Capacity        Status
        192.168.10.68   29a24ea7-a84d-4142-a412-b7fb83fbc695    Unavailable     Unavailable     In Maintenance (This node)
Global Storage Pool
        Total Used      :  0 B
        Total Capacity  :  0 B

AlertID Resource        ResourceID                              Timestamp                       Severity        AlertType          Description
2       NODE            29a24ea7-a84d-4142-a412-b7fb83fbc695    Jul 11 01:30:36 UTC 2017        ALARM           Cluster manager failure     Could not start cluster manager because of: Failed to mount device UUID e7987d9c-b2e1-4a35-9718-fe7981045fb6, dev path /dev/sdc at /var/.px/0: error no such device

$ sudo -i blkid
/dev/sdb: UUID="e7987d9c-b2e1-4a35-9718-fe7981045fb6" UUID_SUB="8fa72d6c-aa94-4c20-bc36-a8cbcd9f59a9" TYPE="btrfs"
/dev/sdc: UUID="e7987d9c-b2e1-4a35-9718-fe7981045fb6" UUID_SUB="fa5a359e-3da6-4b18-97aa-b78a3f439118" TYPE="btrfs"

**Comment by jvinod** [comment]
Hi @abienkowski - could you send us the output of docker logs <px_container> ? Also, could you let us know how PX was started? 
To get out of this situation, you can try `/opt/pwx/bin/pxctl service maintenance --exit` - 
Thanks

**Comment by venkatpx** [comment]
This was an issue with the absolute path of where the storage modules were to be loaded as the module dependencies weren't setup properly in the system and it was solved by loading them before hand
