### ISSUE TITLE
Increase device size

### ISSUE THREAD

**Issue by galindro** [portworx/px-dev#37]
How could I increase an AWS EC2 EBS drive in portworx that has increased in AWS?

I've build a cluster with 3 docker swarm nodes and installed portworx as a docker plugin. I've attached, for testing purposes, 2x 1GB EBS backed disks in each node. This is the cluster status:

```bash
root@swarm-manager-001:/tmp/stacks# /opt/pwx/bin/pxctl status
Status: PX is operational
Node ID: 621ff80d-c47f-42e0-9ab2-fc67dba0b688
	IP: 10.0.1.101 
 	Local Storage Pool: 1 pool
	POOL	IO_PRIORITY	RAID_LEVEL	USABLE	USED	STATUS	ZONE	REGION
	0	MEDIUM		raid0		2.0 GiB	225 MiB	Online	a	sa-east-1
	Local Storage Devices: 2 devices
	Device	Path		Media Type		Size		Last-Scan
	0:1	/dev/xvdg	STORAGE_MEDIUM_MAGNETIC	1.0 GiB		11 Jul 17 12:44 UTC
	0:2	/dev/xvdh	STORAGE_MEDIUM_MAGNETIC	1.0 GiB		11 Jul 17 12:44 UTC
	total			-			2.0 GiB
Cluster Summary
	Cluster ID: socialbase
	IP		ID					Used	Capacity	Status
	10.0.1.101	621ff80d-c47f-42e0-9ab2-fc67dba0b688	225 MiB	2.0 GiB		Online (This node)
	10.0.2.102	31a1ff1f-4e12-4a73-9fae-9009ce855144	225 MiB	2.0 GiB		Online
	10.0.3.103	b6505999-5415-422e-9b89-c9dac8e6bf51	225 MiB	2.0 GiB		Online
Global Storage Pool
	Total Used    	:  676 MiB
	Total Capacity	:  6.0 GiB
```

I've extended the size of 4 EBS disks to 2GB. Two of the 4 resized EBS disks are attached to node 10.0.1.101 and the other 2 are attached to 10.0.2.102 and 10.0.3.103:

![image](https://user-images.githubusercontent.com/4622097/28068957-06f00aaa-661e-11e7-933e-33b1fd455d92.png)

Now I need to reflect the resize action that I did in AWS EC2 EBS console in the portworx cluster. How could I do it?

References:
http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ebs-expand-volume.html#console-modify
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-expand-volume.html#recognize-expanded-volume-linux

**Comment by venkatpx** [comment]
@galindro As discussed in the other threads, the best way to increase the size of a pool is to add new drives of similar size or more nodes with additional storage
