### ISSUE TITLE
max-count parameter

### ISSUE THREAD

**Issue by galindro** [portworx/px-dev#41]
The docs aren't clear about `max-count` parameter: https://docs.portworx.com/cloud/aws/asg.html#scaling-the-cluster-up. Where I need to set it? I mean, what is its correct syntax? Is it a command line parameter or a configuration that needs to be set through environment variable? Is it works with px-dev?

**Comment by galindro** [comment]
@venkatpx

**Comment by venkatpx** [comment]
It should work with px-dev.
Max count is related to the max count of EBS volumes and should be set in user-data in cloud-init. 

Example:
#cloud-config

portworx:
  config:
    storage:
      devices:
      - vol-0743df7bf5657dad8
      - vol-0055e5913b79fb49d
      max-count: 10

**Comment by galindro** [comment]
@venkatpx, is this userdata work with PX Docker plugin too?

**Comment by jvinod** [comment]
Hi @galindro this should work with PX Docker plugin as well.
