### ISSUE TITLE
Maven build fails to checkout to local repository on volume mounted with px driver

### ISSUE THREAD

**Issue by ghost** [portworx/px-dev#44]
using Jenkins master/slave docker containers and Rancher as the orchestration platform, I've setup jenkins-slave instance to mount a m2-repository volume created with pxctl command line tool.

When running a maven build, the process starts to checkout project dependencies to local ~/.m2 repository which is a volume manages by px.

The process creates required directories for first dependency and a lastUpdated file with size 0 bytes, all owned by root, yet the process runs under jenkins-slave user.  The build then fails with IOException.

I've tried the same setup under no volume and under convoy volume with drivermapper driver and have no issues there.  The maven build checks out all dependencies and stores them on ~/.m2 directory with correct permissions.

**Comment by venkatpx** [comment]
@abienkowski-ethoca can you add px container logs so we can see any px errors. Also attach output of pxctl status

**Comment by venkatpx** [comment]
@abienkowski-ethoca did you get a chance to get the above info?

**Comment by venkatpx** [comment]
Closing this issue as we didn't get any further information on it. Pls reopen it once you get more info
