### ISSUE TITLE
Replacing a filed disk

### ISSUE THREAD

**Issue by abienkowski** [portworx/px-dev#47]
In my scenario, my virtualized local disk was removed from one of the nodes, and I replaced it with another volume.

px driver starts in maintenance mode, because it can not find the original /dev/sdd device with a specific uuid.  I've added a new device to replace it, and expected the process to start initializing the new device and replicating data from the second node.

I've also tried pxctl sv drive add /dev/sdc, but it keeps failing because of maintenance mode.

Is there another step that is needed, --recover to exit maintenance mode does not help to recover the situation.

**Comment by venkatpx** [comment]
@abienkowski Have you tried the replace command?

https://docs.portworx.com/maintain/maintenance-mode.html#replace-a-drive-that-is-already-part-of-the-portworx-cluster

**Comment by svensp** [comment]
+1
The drive replace command seems to expect to transfer the data from an existing drive to a new one.
For me the old drive died and was replaced by the hoster in a single step so a transfer was not possible.
`sudo /opt/pwx/bin/pxctl sv drive replace --source /dev/sdc --target /dev/sdc -o start` fails because the old drive with the data is not there.

**Comment by prabirpaul** [comment]
@abienkowski @svensp drive replace helps in the case of failing drives, it doesn't work for completely failed/lost drives. Unfortunately in raid0 configuration it is not possible to recover a completely failed/lost drive. Recovery in this case is to remove this node from the cluster, HA reduce all affected volumes, reinit this node and add back to the cluster and HA add again. Keep in mind this would only recover volumes with replication factor >1.

**Comment by venkatpx** [comment]
We will  also update our documentation to show how to perform this with pxctl
