### ISSUE TITLE
Kubernetes install option

### ISSUE THREAD

**Issue by rimusz** [portworx/px-dev#5]
px-lite had Kubernetes install readme, would be nice to have the same section here as well

**Comment by jvinod** [comment]
ping @erickhan 

Thanks for point that out @rimusz

**Comment by mattbates** [comment]
This [doc](https://github.com/portworx/px-dev/blob/master/install_with_k8s.md) appears to be pretty up-to-date. You might want to link to it in the main docs.

**Comment by jvinod** [comment]
@mattbates @rimusz the doc is updated. Thanks @adityadani
