### ISSUE TITLE
CoreOS + Swarm - Volume Plugin not added autm.

### ISSUE THREAD

**Issue by Berndinox** [portworx/px-dev#50]
I followed the Instruction to install Portworx on Coreos.
https://docs.portworx.com/install/coreos.html

`docker info`
does not shows the pxd Driver!

After doing something like
docker run -it -v my_pxd_vol:/test busybox echo foo
`docker info` now shows the pxd volume and i can start using it with swarm.

That occours after every reboot.. very anoying!

**Comment by venkatpx** [comment]
@senpx can you please follow up on this?

**Comment by Berndinox** [comment]
Seems like the issues also exists with some other volume plugins, may a docker bug?

**Comment by senpx** [comment]
can you please reply the outcome for below commands? and also coreos cluster details.
1. docker info
2. /opt/pwx/bin/pxctl -v
3. /opt/pwx/bin/pxctl status

**Comment by venkatpx** [comment]
Portworx now supports running PX as OCI container and not as plugin. Suggest trying installing PX this way. https://docs.portworx.com/runc/
