### ISSUE TITLE
Start/Stop systemd scripts for portworx standalone setup

### ISSUE THREAD

**Issue by rajivece** [portworx/px-dev#51]
I have successfully set up px-enterprise using below link

> https://docs.portworx.com/scheduler/docker/install-standalone.html

Now I looking for systemd start/stop script for this setup.  Does anyone try the similar option given in below link?

> https://docs.portworx.com/scheduler/docker/install-standalone.html

**Comment by venkatpx** [comment]
@rajivece Pls try this https://github.com/portworx/terraporx/tree/master/automation/ansible for setting up px as a systemd service
