### ISSUE TITLE
Can't initialize pwx-dev with ETCD SSL

### ISSUE THREAD

**Issue by segator** [portworx/px-dev#54]
`{
    "alertingurl": "",
    "cafile": "/etc/pwx/server.ca.crt",
    "certfile": "/etc/pwx/client.crt",
    "certkey": "/etc/pwx/client.key.insecure",
    "clusterid": "mycluster",
    "dataiface": "flannel.1",
    "kvdb": [
        "etcd://my.etcd:2379"
    ],
    "mgtiface": "flannel.1",
    "scheduler": "none",
    "storage": {
        "devices": [
            "/dev/mylvm/portworx"
        ]
    },
    "version": "1.0"
}
`
it seems portworx don't detect etcd is over SSL, I get this error:
Error in obtaining etcd version: Get http://my.etcd:2379/version: malformed HTTP response \\\"\\\\x15\\\\x03\\\\x01\\\\x00\\\\x02\\\\x02\\\

**Comment by adityadani** [comment]
@segator The kvdb url in you config.json should be of the following format
```
"kvdb": ["etcd:https://my.etcd:2379"]
```
By default PX would use http.

**Comment by segator** [comment]
Hi, I tried before but I got this message
Error in obtaining etcd version: Get http:https//my.etcd:2379/version: http: no Host in request URL.

**Comment by pault84** [comment]
can you share what is in your config.json?
is it http://https
or etcd://https?

**Comment by segator** [comment]
Ok thank you.. missing dots.

One question I see that is enabled by default the enterprise version with 30 days trial, after  30 days automatically will be free version? I don't see any point on the documentation to install the px-dev version as a docker plugin

**Comment by senpx** [comment]
@segator can you paste your config.json? and also which command used to run px?

**Comment by segator** [comment]
Hi, finally installed portworx as runC. works fine but no key/value saved on ETCD.

`{
    "alertingurl": "",
    "cafile": "/etc/pwx/server.ca.crt",
    "certfile": "/etc/pwx/client.crt",
    "certkey": "/etc/pwx/client.key.insecure",
    "clusterid": "portworx",
    "dataiface": "flannel.1",
    "kvdb": [
        "etcd:https://etcd.service.com:2379"
    ],
    "mgtiface": "eth4",
    "scheduler": "none",
    "storage": {
        "devices": [
            "/dev/lvm/portworx"
        ]
    },
    "version": "1.0"
}
`
