### ISSUE TITLE
Failed with error: Scan found old metadata drives

### ISSUE THREAD

**Issue by AlvinLv00** [portworx/px-dev#60]
Reinitialize the node and the following error occurs：

time="2018-05-17T09:18:16Z" level=error msg="hal.Reinit() Failed with error: **Scan found old metadata drives"** 
time="2018-05-17T09:18:16Z" level=info Error=<nil> Function=nodeMap.Add MID=79de5140-abec-4b60-9af3-bb4554f25bf8 NID=15 Status=InitializationError Version= 
time="2018-05-17T09:18:16Z" level=warning msg="**Failed to initialize Init PX Storage Service: Storage failed initialization**" 
time="2018-05-17T09:18:16Z" level=info msg="Cleanup Init services" 
time="2018-05-17T09:18:16Z" level=warning msg="Cleanup Init for service Scheduler." 
time="2018-05-17T09:18:16Z" level=info msg="Cleanup Initializing node and joining the cluster 5ac2ed6f-7e4e-4e1d-8e8c-3a6df1fb61a5..." 
time="2018-05-17T09:18:16Z" level=warning msg="Cleanup Init for service PX Storage Service." 
time="2018-05-17T09:18:16Z" level=info msg="Cleanup Init for Storage provider PXD" 
time="2018-05-17T09:18:16Z" level=error msg="Failed to initialize node in cluster. Storage failed initialization" 
time="2018-05-17T09:18:16Z" level=error msg="Cluster Manager Failure: Storage failed initialization" 
time="2018-05-17T09:18:16Z" level=warning msg="Removing /etc/pwx/.private.json" 
time="2018-05-17T09:18:16Z" level=info msg="Forcing the rescan of Docker drivers" 
time="2018-05-17T09:18:16Z" level=error msg="Error while calling home: HTTP-500: Unavailable****

**Comment by adityadani** [comment]
@lxtxlxl To reinitialize a PX node, you need to wipe the node of old PX fingerprint data. You can do that by running the following command on that node

```
$ /opt/pwx/bin/pxctl service node-wipe
```

Note that above command is going to wipe all the data from the storage devices that were provided to PX.
