### ISSUE TITLE
 Snapshot policy is not triggered

### ISSUE THREAD

**Issue by matrixyisi** [portworx/px-dev#63]
I set the policy according to the official example, but the policy has not been triggered and the snapshot has not been generated
------------------------------------
root@ubuntu:~#pxctl v i myvol
Volume	:  657546747400649879
	Name            	 :  myvol
	Size            	 :  1.0 GiB
	Format          	 :  ext4
	HA              	 :  1
	IO Priority     	 :  LOW
	Creation time   	 :  Jun 6 07:04:13 UTC 2018
	Snapshot        	 :  periodic 1h0m0s,keep last 5, daily @07:10,keep last 7, weekly Friday@23:30,keep last 5, monthly 1@06:00,keep last 12
	Shared          	 :  no
	Status          	 :  up
	State           	 :  Attached: f06af468-4a33-4894-9878-c8780f2186a1
	Device Path     	 :  /dev/pxd/pxd657546747400649879
	Reads           	 :  6
	Reads MS        	 :  4
	Bytes Read      	 :  24576
	Writes          	 :  43
	Writes MS       	 :  144
	Bytes Written   	 :  16887808
	IOs in progress 	 :  0
	Bytes used      	 :  32 MiB
	Replica sets on nodes:
		Set  0
		  Node 		 :  192.168.109.142 (Pool 0)  
	Replication Status

---------

root@ubuntu:~# pxctl v l
ID			NAME		SIZE	HA	SHARED	ENCRYPTED	COMPRESSED	IO_PRIORITY	SCALE	STATUS
657546747400649879	myvol		1 GiB	1	no	no		no		LOW		1	up - attached on 192.168.109.142
703791940441643237	pxd_vol		1 GiB	1	no	no		no		LOW		1	up - detached
1021764939152725027	s1		1 GiB	1	no	no		no		LOW		1	up - detached
392950682941227731	test2_pxd	1 GiB	1	no	no		no		LOW		0	up - detached
809450042622907701	test_pxd	1 GiB	1	no	no		no		LOW		0	up - detached
309907089682248514	ts		1 GiB	3	yes	no		no		LOW		1	up - attached on 192.168.109.142
-----------
root@ubuntu:~# pxctl -v
pxctl version 1.3.1.1-53b335b

**Comment by sangleganesh** [comment]
To view schedule snapshots, the filters are "pxctl v l -s". Can you check the output of that command ? Thanks.
