### ISSUE TITLE
How to Rebuild pwx.ko on airgapped server?

### ISSUE THREAD

**Issue by cneth** [portworx/px-dev#7]
I'm trying to run the container on CoreOS 1010.5.0 on an airgapped server (our clusters have an internal registry - nodes do not have access to the 'internet'.

It looks like the container rebuilds the pwx.ko as part of the startup.  This is failing for me because I am running the container on an airgapped server that does not have a path back to the various mirrors.

What's the solution?

Some snippets from the log:

...
Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
....

time="2016-06-30T22:14:01Z" level=error msg="Kernel Driver error detected... please load the correct PX kernel module and restart: Kernel Driver Error" 
2016-06-30 22:14:01,264 INFO exited: px (exit status 255; not expected)

**Comment by jvinod** [comment]
@cneth please try with 
```
-v /lib/modules:/lib/modules 

```
Newer coreos releases ship with kernel headers and the container will not try to get the headers from an external yum repo if it finds it there.

Let us also know the output of:
```
uname -a
```

**Comment by jsilberm** [comment]
@cneth Glad it worked.   Nice meeting you in Seattle.

-Jeff
