### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by marco-m** [portworx/px-dev#76]
Hello, last code commit to this repo is more than one year ago, Aug 2018.

Could portworx tell the open source community what is the future of px-dev? Is the only option now the Enterprise version?

Thanks!

**Comment by mh720** [comment]
Not sure what this project represents, I see a Dockerfile building from portworx/px-base. The official px-dev container image is maintained by Portworx and receives updates at https://hub.docker.com/r/portworx/px-dev 

Also, check out https://github.com/swarmstack/swarmstack - which points at that image by default.

**Comment by marco-m** [comment]
@mh720 thanks!
