### ISSUE TITLE
etcd needs for px-dev on kubernetes

### ISSUE THREAD

**Issue by rimusz** [portworx/px-dev#8]
Does px-dev on kubernetes need etcd?
It is not mentioned in https://github.com/portworx/px-dev/blob/master/install_with_k8s.md

**Comment by jsilberm** [comment]
@rimusz : px-dev requires some distributed key-value db, as described in the config.json file :  https://github.com/portworx/px-dev/tree/master/conf .   etcd or consul are both supported :   https://github.com/portworx/kvdb
